services:
  pet:
    build: ./services/pet
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - SERVER_PORT=5001
      - DB_HOST=fdb
      - DB_PORT=5432
      - DB_NAME=BotsMemory
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=public
      - JWT_SECRET=UmisTestSignKey
  clinic:
    build: ./services/clinic
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - SERVER_PORT=5002
      - DB_HOST=sdb
      - DB_PORT=5432
      - DB_NAME=BotsMemory
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=public
      - JWT_SECRET=UmisTestSignKey
  images:
    build: ./services/fileuploader
    restart: unless-stopped
    ports:
      - "5003:5003"
    environment:
      - SERVER_PORT=5003
  api-gateway:
    build: ./api-gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PET_SERVICE_URL=http://pet:5001
      - CLINIC_SERVICE_URL=http://clinic:5002
      - FILEUPLOADER_SERVICE_URL=http://images:5003
      - PORT=5000
  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  fdb:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BotsMemory
    ports:
      - "5433:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
  sdb:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BotsMemory
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
volumes:
  pgdata1:
  pgdata2: