services:
  pet:
    build: ./services/pet
    ports:
      - "5001:5001"
    environment:
      - SERVER_PORT=5001
      - DB_HOST=ep-round-paper-091468-pooler.us-east-2.aws.neon.tech
      - DB_PORT=5432
      - DB_NAME=BotsMemory
      - DB_USER=maxim7012
      - DB_PASSWORD=npg_e1j3CoBsItyd
      - DB_SCHEMA=public
      - JWT_SECRET=UmisTestSignKey
  clinic:
    build: ./services/clinic
    ports:
      - "5002:5002"
    environment:
      - SERVER_PORT=5002
      - DB_HOST=ep-round-paper-091468-pooler.us-east-2.aws.neon.tech
      - DB_PORT=5432
      - DB_NAME=Shop
      - DB_USER=postgres
      - DB_PASSWORD=gaTResKPJX25
      - DB_SCHEMA=public
      - JWT_SECRET=UmisTestSignKey
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - PET_SERVICE_URL=http://pet:5001
      - CLINIC_SERVICE_URL=http://clinic:5002
      - PORT=5000
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
